[project]
name = "mcp-streamlit"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "mcp[cli]>=1.12.1",
    "openai>=1.96.1",
    "streamlit>=1.46.1",
]
